module.exports = {
  "2B": "2345 Browser",
  "36": "360 Phone Browser",
  "3B": "360 Browser",
  "AA": "Avant Browser",
  "AB": "ABrowse",
  "AF": "ANT Fresco",
  "AG": "ANTGalio",
  "AL": "Aloha Browser",
  "AM": "Amaya",
  "AO": "Amigo",
  "AN": "Android Browser",
  "AD": "AOL Shield",
  "AR": "Arora",
  "AV": "Amiga Voyager",
  "AW": "Amiga Aweb",
  "AT": "Atomic Web Browser",
  "AS": "Avast Secure Browser",
  "BA": "Beaker Browser",
  "BB": "BlackBerry Browser",
  "BD": "Baidu Browser",
  "BS": "Baidu Spark",
  "BE": "Beonex",
  "BJ": "Bunjalloo",
  "BL": "B-Line",
  "BR": "Brave",
  "BK": "BriskBard",
  "BX": "BrowseX",
  "CA": "Camino",
  "CC": "Coc Coc",
  "CD": "Comodo Dragon",
  "C1": "Coast",
  "CX": "Charon",
  "CE": "CM Browser",
  "CF": "Chrome Frame",
  "HC": "Headless Chrome",
  "CH": "Chrome",
  "CI": "Chrome Mobile iOS",
  "CK": "Conkeror",
  "CM": "Chrome Mobile",
  "CN": "CoolNovo",
  "CO": "CometBird",
  "CP": "ChromePlus",
  "CR": "Chromium",
  "CY": "Cyberfox",
  "CS": "Cheshire",
  "CU": "Cunaguaro",
  "CV": "Chrome Webview",
  "DB": "dbrowser",
  "DE": "Deepnet Explorer",
  "DF": "Dolphin",
  "DO": "Dorado",
  "DL": "Dooble",
  "DI": "Dillo",
  "DD": "DuckDuckGo Privacy Browser",
  "EC": "Ecosia",
  "EI": "Epic",
  "EL": "Elinks",
  "EB": "Element Browser",
  "EP": "GNOME Web",
  "ES": "Espial TV Browser",
  "F1": "Firefox Mobile iOS",
  "FB": "Firebird",
  "FD": "Fluid",
  "FE": "Fennec",
  "FF": "Firefox",
  "FK": "Firefox Focus",
  "FR": "Firefox Rocket",
  "FL": "Flock",
  "FM": "Firefox Mobile",
  "FW": "Fireweb",
  "FN": "Fireweb Navigator",
  "GA": "Galeon",
  "GE": "Google Earth",
  "HJ": "HotJava",
  "IB": "IBrowse",
  "IC": "iCab",
  "I2": "iCab Mobile",
  "I1": "Iridium",
  "I3": "Iron Mobile",
  "I4": "IceCat",
  "ID": "IceDragon",
  "IV": "Isivioo",
  "IW": "Iceweasel",
  "IE": "Internet Explorer",
  "IM": "IE Mobile",
  "IR": "Iron",
  "JS": "Jasmine",
  "JI": "Jig Browser",
  "KI": "Kindle Browser",
  "KM": "K-meleon",
  "KO": "Konqueror",
  "KP": "Kapiko",
  "KW": "Kiwi",
  "KY": "Kylo",
  "KZ": "Kazehakase",
  "LB": "Cheetah Browser",
  "LF": "LieBaoFast",
  "LG": "LG Browser",
  "LI": "Links",
  "LU": "LuaKit",
  "LS": "Lunascape",
  "LX": "Lynx",
  "MB": "MicroB",
  "MC": "NCSA Mosaic",
  "ME": "Mercury",
  "MF": "Mobile Safari",
  "MI": "Midori",
  "MO": "Mobicip",
  "MU": "MIUI Browser",
  "MS": "Mobile Silk",
  "MT": "Mint Browser",
  "MX": "Maxthon",
  "NB": "Nokia Browser",
  "NO": "Nokia OSS Browser",
  "NV": "Nokia Ovi Browser",
  "NE": "NetSurf",
  "NF": "NetFront",
  "NL": "NetFront Life",
  "NP": "NetPositive",
  "NS": "Netscape",
  "NT": "NTENT Browser",
  "O1": "Opera Mini iOS",
  "OB": "Obigo",
  "OD": "Odyssey Web Browser",
  "OF": "Off By One",
  "OE": "ONE Browser",
  "OG": "Opera Neon",
  "OH": "Opera Devices",
  "OI": "Opera Mini",
  "OM": "Opera Mobile",
  "OP": "Opera",
  "ON": "Opera Next",
  "OO": "Opera Touch",
  "OR": "Oregano",
  "OV": "Openwave Mobile Browser",
  "OW": "OmniWeb",
  "OT": "Otter Browser",
  "PL": "Palm Blazer",
  "PM": "Pale Moon",
  "PP": "Oppo Browser",
  "PR": "Palm Pre",
  "PU": "Puffin",
  "PW": "Palm WebPro",
  "PA": "Palmscape",
  "PX": "Phoenix",
  "PO": "Polaris",
  "PT": "Polarity",
  "PS": "Microsoft Edge",
  "Q1": "QQ Browser Mini",
  "QQ": "QQ Browser",
  "QT": "Qutebrowser",
  "QZ": "QupZilla",
  "QM": "Qwant Mobile",
  "QW": "QtWebEngine",
  "RK": "Rekonq",
  "RM": "RockMelt",
  "SB": "Samsung Browser",
  "SA": "Sailfish Browser",
  "SC": "SEMC-Browser",
  "SE": "Sogou Explorer",
  "SF": "Safari",
  "SH": "Shiira",
  "SK": "Skyfire",
  "SS": "Seraphic Sraf",
  "SL": "Sleipnir",
  "SN": "Snowshoe",
  "SO": "Sogou Mobile Browser",
  "SR": "Sunrise",
  "SP": "SuperBird",
  "ST": "Streamy",
  "SX": "Swiftfox",
  "SZ": "Seznam Browser",
  "TF": "TenFourFox",
  "TB": "Tenta Browser",
  "TZ": "Tizen Browser",
  "TS": "TweakStyle",
  "UC": "UC Browser",
  "UM": "UC Browser Mini",
  "VI": "Vivaldi",
  "VB": "Vision Mobile Browser",
  "WP": "Web Explorer",
  "WE": "WebPositive",
  "WF": "Waterfox",
  "WH": "Whale Browser",
  "WO": "wOSBrowser",
  "WT": "WeTab Browser",
  "YA": "Yandex Browser",
  "XI": "Xiino"
};