// prettier-ignore
module.exports = {
	'Android': ['AND', 'CYN', 'FIR', 'REM', 'RZD', 'MLD', 'MCD', 'YNS', 'GRI'],
	'AmigaOS': ['AMG', 'MOR'],
	'Apple TV': ['ATV'],
	'BlackBerry': ['BLB', 'QNX'],
	'Brew': ['BMP'],
	'BeOS': ['BEO', 'HAI'],
	'Chrome OS': ['COS', 'FYD', 'SEE'],
	'Firefox OS': ['FOS', 'KOS'],
	'Gaming Console': ['WII', 'PS3'],
	'Google TV': ['GTV'],
	'IBM': ['OS2'],
	'iOS': ['IOS', 'WAS'],
	'RISC OS': ['ROS'],
	'GNU/Linux': [
		'LIN', 'ARL', 'DEB', 'KNO', 'MIN', 'UBT', 'KBT', 'XBT', 'LBT', 'FED',
		'RHT', 'VLN', 'MDR', 'GNT', 'SAB', 'SLW', 'SSE', 'CES', 'BTR', 'SAF',
		'ORD', 'TOS', 'RSO', 'DEE', 'FRE', 'MAG', 'FEN', 'CAI', 'PCL', 'HAS',
		'LOS', 'DVK',
	],
	'Mac': ['MAC'],
	'Mobile Gaming Console': ['PSP', 'NDS', 'XBX'],
	'Real-time OS': ['MTK', 'TDX', 'MRE'],
	'Other Mobile': ['WOS', 'POS', 'SBA', 'TIZ', 'SMG', 'MAE'],
	'Symbian': ['SYM', 'SYS', 'SY3', 'S60', 'S40'],
	'Unix': [
		'SOS',
		'AIX',
		'HPX',
		'BSD',
		'NBS',
		'OBS',
		'DFB',
		'SYL',
		'IRI',
		'T64',
		'INF'],
	'WebTV': ['WTV'],
	'Windows': ['WIN'],
	'Windows Mobile': ['WPH', 'WMO', 'WCE', 'WRT', 'WIO'],
	'Other Smart TV': ['WHS'],
};
