// prettier-ignore
module.exports = {
	'AIX': 'AIX',
	'AND': 'Android',
	'AMG': 'AmigaOS',
	'ATV': 'Apple TV',
	'ARL': 'Arch Linux',
	'BTR': 'BackTrack',
	'SBA': 'Bada',
	'BEO': 'BeOS',
	'BLB': 'BlackBerry OS',
	'QNX': 'BlackBerry Tablet OS',
	'BMP': 'Brew',
	'CAI': 'Caixa Mágica',
	'CES': 'CentOS',
	'COS': 'Chrome OS',
	'CYN': 'CyanogenMod',
	'DEB': 'Debian',
	'DEE': 'Deepin',
	'DFB': 'DragonFly',
	'DVK': 'DVKBuntu',
	'FED': 'Fedora',
	'FEN': 'Fenix',
	'FOS': 'Firefox OS',
	'FIR': 'Fire OS',
	'FRE': 'Freebox',
	'BSD': 'FreeBSD',
	'FYD': 'FydeOS',
	'GNT': 'Gentoo',
	'GRI': 'GridOS',
	'GTV': 'Google TV',
	'HPX': 'HP-UX',
	'HAI': 'Haiku OS',
	'HAS': 'HasCodingOS',
	'IRI': 'IRIX',
	'INF': 'Inferno',
	'KOS': 'KaiOS',
	'KNO': 'Knoppix',
	'KBT': 'Kubuntu',
	'LIN': 'GNU/Linux',
	'LBT': 'Lubuntu',
	'LOS': 'Lumin OS',
	'VLN': 'VectorLinux',
	'MAC': 'Mac',
	'MAE': 'Maemo',
	'MAG': 'Mageia',
	'MDR': 'Mandriva',
	'SMG': 'MeeGo',
	'MCD': 'MocorDroid',
	'MIN': 'Mint',
	'MLD': 'MildWild',
	'MOR': 'MorphOS',
	'NBS': 'NetBSD',
	'MTK': 'MTK / Nucleus',
	'MRE': 'MRE',
	'WII': 'Nintendo',
	'NDS': 'Nintendo Mobile',
	'OS2': 'OS/2',
	'T64': 'OSF1',
	'OBS': 'OpenBSD',
	'ORD': 'Ordissimo',
	'PCL': 'PCLinuxOS',
	'PSP': 'PlayStation Portable',
	'PS3': 'PlayStation',
	'RHT': 'Red Hat',
	'ROS': 'RISC OS',
	'RSO': 'Rosa',
	'REM': 'Remix OS',
	'RZD': 'RazoDroiD',
	'SAB': 'Sabayon',
	'SSE': 'SUSE',
	'SAF': 'Sailfish OS',
	'SEE': 'SeewoOS',
	'SLW': 'Slackware',
	'SOS': 'Solaris',
	'SYL': 'Syllable',
	'SYM': 'Symbian',
	'SYS': 'Symbian OS',
	'S40': 'Symbian OS Series 40',
	'S60': 'Symbian OS Series 60',
	'SY3': 'Symbian^3',
	'TDX': 'ThreadX',
	'TIZ': 'Tizen',
	'TOS': 'TmaxOS',
	'UBT': 'Ubuntu',
	'WAS': 'watchOS',
	'WTV': 'WebTV',
	'WHS': 'Whale OS',
	'WIN': 'Windows',
	'WCE': 'Windows CE',
	'WIO': 'Windows IoT',
	'WMO': 'Windows Mobile',
	'WPH': 'Windows Phone',
	'WRT': 'Windows RT',
	'XBX': 'Xbox',
	'XBT': 'Xubuntu',
	'YNS': 'YunOs',
	'IOS': 'iOS',
	'POS': 'palmOS',
	'WOS': 'webOS',
};
